project_name: skipper

builds:
  - binary: skipper
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags:
      - -s -w -X github.com/jerryagbesi/skipper/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  use: github
  groups:
    - title: "Breaking Changes"
      regexp: '^.*?[a-z]+(\([\w\-\.]+\))?!:.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\([\w\-\.]+\))?!?:.+$'
      order: 1
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([\w\-\.]+\))?!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: JerryAgbesi
    name: skipper
  header: |
    See the full [CHANGELOG.md](https://github.com/JerryAgbesi/skipper/blob/v{{ .Version }}/CHANGELOG.md) for details and migration notes.
